import java.util.ArrayList;

public class ProjectEuler2 {
	//Project Euler Problem 2: Even Fibonacci Numbers
	//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
	//By starting with 1 and 2, the first 10 terms will be:
	//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	//By considering the terms in the Fibonacci sequence whose values 
	//do not exceed four million, find the sum of the even-valued terms.
	
	public static void main(String [] args) {
		ArrayList<Integer> number = new ArrayList<Integer>();		
		
		number.add(1);
		number.add(2);
		int evenSum = 2;
		for(int i = 2; ; i++) {
			int last2 = number.get(i-1) + number.get(i-2);
			if(last2 <= 4000000) {
				number.add(last2);
				if((last2 % 2) == 0) {
					evenSum += last2;
				}
			}
			else {
				break;
			}
		}

		System.out.println("The Sum of the even Fibonacci terms: "+ evenSum);
		
	}
	
}
